<header>
        <div id="logo">
            <h1><a class="logo title" href="<?php echo $this->url(
                    array('controller'=>'index', 'action' => 'index'),
                    'default',
                    true) ?>" title="GroenGent">GroenGent</a></h1>
            <a href="#" class="btn-user" data-role="button" data-icon="grid" data-iconpos="notext" data-theme="c" data-inline="true">Menu</a>
        </div>
        
        <?php if($this->loggedin == 0):?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'login'),
                        'default',
                        true) ?>" title="Aanmelden" class="btn-primary" data-ajax="false">Aanmelden</a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'register'),
                        'default',
                        true) ?>" title="Registreren" class="btn" data-ajax="false">Registreren</a>
             </div>
         </section>
         
         <section id="nav-mobile">         
             <div id="navbar-mobile" data-role="navbar">
                <ul>
                    <li><a href="#" title="Info" class="ui-btn-active" id="mobileInfo" data-role="button" data-icon="info"></a></li>
                    <li><a href="#" title="Lijst" id="mobileLijst" data-role="button" data-icon="bars"></a></li>
                    <li><a href="#" title="Kaart" id="mobileKaart" data-role="button" data-icon="search"></a></li>
                </ul>
            </div>
         </section>
    <?php else: ?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" class="" data-ajax="false"><?php echo "Hallo " . $this->username; ?></a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" class="" data-ajax="false">Afmelden</a>
             </div>
         </section>
         
         <section id="nav-mobile">         
         	<a href="#" title="Navigation menu" data-icon="grid" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" class="menuBtn ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text"></span>
                    <span class="" data-ajax="false"></span>
                </span>
            </a>
        <?php endif; ?>
    
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" alt="GroenGent" data-transition="sliceDown"     />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" alt="GroenGent" data-transition="slideInLeft"   />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" alt="GroenGent" data-transition="boxRandom"     />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" alt="GroenGent" data-transition="boxRain"       />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" alt="GroenGent" data-transition="slideInRight"  />
            </div>
        </div>
    </header>

    <div id="menu-mobile">
        <ul>
            <li><a href="<?php echo $this->url(
                array('controller'=>'account', 'action' => 'login'),
                'default',
                true) ?>" title="Aanmelden" data-ajax="false" data-role="button" data-icon="check" data-theme="b" class="txtWhite">Aanmelden</a></li>
            <li><a href="<?php echo $this->url(
                array('controller'=>'account', 'action' => 'register'),
                'default',
                true) ?>" title="Registreren" class="btn" data-ajax="false" data-role="button" data-icon="edit" data-theme="b" class="txtWhite">Registreren</a></li>
            <li><a href="<?php echo $this->url(
                array('controller'=>'account', 'action' => 'forgotpassword'),
                'default',
                true) ?>" title="Wachtwoord vergeten" class="btn" data-ajax="false" data-role="button" data-icon="alert" data-theme="b" class="txtWhite">Wachtwoord vergeten</a></li>
                        
            <li id="mobileDisclaimer"><a href="#" title="Disclaimer" data-role="button" data-inline="true" class="btnFullWidth">Disclaimer</a></li>
            <li id="mobileClose"><a href="#" title="Sluit venster" data-role="button" data-inline="true" class="btnFullWidth">Sluit venster</a></li>
        </ul>
    </div>
    
    <div id="container">
        <section id="content">
            <?php if($this->loggedin == 0):?>
                <div id="intro">
                    <h3>Op naar een Groener Gent!</h3>
                    <img src="<?=$this->baseUrl('_assets/img/img-about.png')?>" alt="Over GroenGent"/>
                    <p>GroenGent biedt veel informatie om je Gentse leven makkelijker te maken! Dankzij GroenGent kan je makkelijk opzoeken in welke gebieden van Gent je het beste gaat picknicken, een uitstap doen, gaat sporten of zélfs solliciteren.</p>
                    <p>Registreer en vergelijk onderstaande data met elkaar!</p>
                </div>
            
            
            <!-- LOGGED IN - Compare -->
            <?php else: ?>
            <div id="compare">
                <h3>Jouw vergelijking:</h3>
                <div id="c1">
                    <h4>Wijken</h4>
                    <ul id="c1UL"></ul>
                </div>
                <div id="c2">
                    <h4>Data #2</h4>
                    <ul id="c2UL"></ul>
                </div>
                <div id="c3">
                    <h4>Conclusie</h4>
                    <p class='oneDS'>Je hebt momenteel <span class='dataSet1'>Wijken</span> geselecteerd. Kies een tweede dataset om een vergelijking te maken.</p>
                    <p class='twoDS'><span class='dataSet1'>Wijken</span> en <span class='dataSet2'>Bebouwde oppervlakte</span> zijn geselecteerd.</p>
                </div>
            </div>
            <?php endif; ?>
            
            <div id="dataFloat" class="ui-grid-a">
                <div id="choose-data" class="ui-block-a">
                    <?php if($this->loggedin == 1):?>
                        <h3>Vergelijk</h3>

                        <?php else: ?>
                        <h3>Weergave</h3>

                    <?php endif; ?>

                    <ul id="selData">
                        <li><span class="liLeft">Wijken</span><span class="liRight"><input type="checkbox" onclick="getData(1)" name="cbxWY" id="cbxWY" checked/></span></li>
                        <li><span class="liLeft">Bebouwde oppervlakte</span><span class="liRight"><input type="checkbox" onclick="getData(2)" name="cbxBO" id="cbxBO"/></span></li>
                        <li><span class="liLeft">Speelterreinen</span><span class="liRight"><input type="checkbox" onclick="getData(3)" name="cbxST" id="cbxST"/></span></li>
                        <li><span class="liLeft">Bevolking/wijk</span><span class="liRight"><input type="checkbox" onclick="getData(4)" name="cbxBW" id="cbxBW"/></span></li>
                        <li><span class="liLeft">Jeugdwerklocaties</span><span class="liRight"><input type="checkbox" onclick="getData(5)" name="cbxJW" id="cbxJW"/></span></li>
                        <li><span class="liLeft">Etnische minderheden</span><span class="liRight"><input type="checkbox" onclick="getData(6)" name="cbxEM" id="cbxEM"/></span></li>
                        <li><span class="liLeft">Werkloosheid > 2 jaar</span><span class="liRight"><input type="checkbox" onclick="getData(7)" name="cbxWL" id="cbxWL"/></span></li>
                        <li><span class="liLeft">Parken</span><span class="liRight"><input type="checkbox" onclick="getData(8)" name="cbxPa" id="cbxPa"/></span></li>
                        <li><span class="liLeft">Parkeergarages</span><span class="liRight"><input type="checkbox" onclick="getData(9)" name="cbxPG" id="cbxPG"/></span></li>
                        <li><span class="liLeft">Parkinglocaties</span><span class="liRight"><input type="checkbox" onclick="getData(10)" name="cbxPL" id="cbxPL"/></span></li>
                        <li><span class="liLeft">Bioscopen</span><span class="liRight"><input type="checkbox" onclick="getData(11)" name="cbxCI" id="cbxCI"/></span></li>
                        <li><span class="liLeft">Sportcentra</span><span class="liRight"><input type="checkbox" onclick="getData(12)" name="cbxSC" id="cbxSC"/></span></li>
                        <li><span class="liLeft">Bibliotheken</span><span class="liRight"><input type="checkbox" onclick="getData(13)" name="cbxBI" id="cbxBI"/></span></li>
                    </ul>
                </div>
                <div id="show-data" class="ui-block-b">
                    <div id="output">
                        <div id="map_canvas"></div>
                    </div>
                </div>
            </div>
        </section>
        
        <footer>
        	<div class="">
            	&copy; Tom Van humbeek, Arteveldehogeschool 2013. <a href="#" title="Disclaimer" class="btn">DISCLAIMER</a>
            </div>
        </footer>
        
        <div id="view-disclaimer">     
            <h2 data-role="header" class="ui-header ui-bar-a ui-title" role="banner" role="heading" aria-level="1">Disclaimer</h2><span class="closeBtn btn">X</span>
        
            <p>Deze web-app werd gebouwd in opdracht van de Arteveldehogeschool.</p>
            
            <p>Niets - zowel visueel, inhoudelijk als technisch - uit deze web-app mag gebruikt of overnomen geworden, zonder volledig akkoord van de maker.</p>
            
            <p>Web-app gemaakt met:</p>
                <ul>
                    <li>PHP [Zend Framework] met MVC</li>
                    <li>RESTful API: kan JSON/JSON-P genereren</li>
                    <li>MySQL</li>
                    <li>HTML5</li>
                    <li>CSS3</li>
                    <li>jQuery</li>
                    <li>Canvas, Twitter Bootstrap, jQuery Mobile</li>
                    <li>Adobe Photoshop</li>
                </ul>
            
            <p class="txtCenter fontSmall">&copy; <a href="http://www.arteveldehogeschool.be" title="Arteveldehogeschool" target="_blank">Arteveldehogeschool Gent</a>, Tom Van humbeek - 2013</p>
            <a href="#" id="mobileClose" data-role="button" data-inline="true" class="btnFullWidth">Terug</a>
        </div>
    </div>
   <div id="overlay"></div>
<script type="text/javascript"
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=true"></script>
<script src="/statghent/public/_scripts/js/geolocation.js"></script>