<header>
        <div id="logo">
        <h1><a class="logo" href="<?php echo $this->url(
                array('controller'=>'index', 'action' => 'index'),
                'default',
                true) ?>" title="GroenGent Home">GroenGent</a></h1>
        </div>
        <?php if($this->loggedin == 0):?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'login'),
                        'default',
                        true) ?>" class="btn btn-primary btn-login">Aanmelden</a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'register'),
                        'default',
                        true) ?>" class="btn btn-secondary btn-register">Registreren</a>
                
             </div>
         </section>
         
        <section id="nav-tablet">
            <div id="buttons-header-tablet">
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'login'),
                        'default',
                        true) ?>" class="btn btn-login">Aanmelden</a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'register'),
                        'default',
                        true) ?>" class="btn btn-register">Registreren</a>
                
             </div>
         </section>
         
         <section id="nav-mobile">         
         	<a href="#" title="Navigation menu" data-icon="grid" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" class="menuBtn ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text"></span>
                    <span class="ui-icon ui-icon-grid ui-icon-shadow" style="margin: -4px 0 0 -4px;"></span>
                </span>
            </a>
         
         <div id="buttons-header-mobile">
         		<a href="<?php echo $this->url(
                            array('controller'=>'account', 'action' => 'login'),
                            'default',
                        true) ?>" data-icon="check" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="loginMobileBtn" class="btn btn-login ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text">Aanmelden</span>
                        <span class="ui-icon ui-icon-check ui-icon-shadow"></span>
                    </span>
                </a>
                
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'register'),
                        'default',
                        true) ?>" data-icon="edit" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="registerMobileBtn" class="btn btn-register ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text">Register</span>
                        <span class="ui-icon ui-icon-edit ui-icon-shadow"></span>
                    </span>
                </a>
                
                <a href="#" title="Disclaimer" id="mobileDisclaimerBtn" data-icon="info" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="#styleMobile" class="btn btn-disclaimer ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                    <span class="ui-btn-inner">
                        <span class="ui-btn-text">Disclaimer</span>
                        <span class="ui-icon ui-icon-info ui-icon-shadow"></span>
                    </span>
                </a>
             </div>
         </section>
    <?php else: ?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" class="btn btn-primary btn-profile"><?php echo "Hallo " . $this->username; ?></a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" class="btn btn-primary btn-profile">Afmelden</a>
                
             </div>
         </section>
         
        <section id="nav-tablet">
            <div id="buttons-header-tablet">
                <a href="<?php echo "Hallo " . $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" class="btn btn-login"><?php echo "Hallo " . $this->username; ?></a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" class="btn btn-register">Afmelden</a>
                
                
             </div>
         </section>
         
         <section id="nav-mobile">         
         	<a href="#" title="Navigation menu" data-icon="grid" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" class="menuBtn ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text"></span>
                    <span class="ui-icon ui-icon-grid ui-icon-shadow" style="margin: -4px 0 0 -4px;"></span>
                </span>
            </a>
         
         <div id="buttons-header-mobile">
         		<a href="<?php echo "Hallo " . $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" data-icon="check" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="profileMobileBtn" class="btn btn-profile ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text"><?php echo "Hallo " . $this->username; ?></span>
                        <span class="ui-icon ui-icon-check ui-icon-shadow"></span>
                    </span>
                </a>
         		<a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" data-icon="check" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="profileMobileBtn" class="btn btn-profile ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text">Logout</span>
                        <span class="ui-icon ui-icon-check ui-icon-shadow"></span>
                    </span>
                </a>
                
                             
                <a href="#" title="Disclaimer" id="mobileDisclaimerBtn" data-icon="info" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="styleMobile" class="btn btn-disclaimer ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                    <span class="ui-btn-inner">
                        <span class="ui-btn-text">Disclaimer</span>
                        <span class="ui-icon ui-icon-info ui-icon-shadow"></span>
                    </span>
                </a>
             </div>
         </section>
    <?php endif; ?>
    
    </header>
    
    <div id="container">
        <section id="content">            
            <div id="choose-data">
                <h3>Vergelijk</h3>
                
                <ul id="selData">
                    <li><span class="liLeft">Wijken</span><span class="liRight"><input type="checkbox" onclick="getData(1)" name="cbxWY" id="cbxWY" checked/></span></li>
                    <li><span class="liLeft">Bebouwde oppervlakte</span><span class="liRight"><input type="checkbox" onclick="getData(2)" name="cbxBO" id="cbxBO"/></span></li>
                    <li><span class="liLeft">Speelterreinen</span><span class="liRight"><input type="checkbox" onclick="getData(3)" name="cbxST" id="cbxST"/></span></li>
                    <li><span class="liLeft">Bevolking/wijk</span><span class="liRight"><input type="checkbox" onclick="getData(4)" name="cbxBW" id="cbxBW"/></span></li>
                    <li><span class="liLeft">Jeugdwerklocaties</span><span class="liRight"><input type="checkbox" onclick="getData(5)" name="cbxJW" id="cbxJW"/></span></li>
                    <li><span class="liLeft">Bevolking/leeftijd: '01-'11</span><span class="liRight"><input type="checkbox" onclick="getData(6)" name="cbxBS" id="cbxBS"/></span></li>
                    <li><span class="liLeft">Etnische minderheden</span><span class="liRight"><input type="checkbox" onclick="getData(7)" name="cbxEM" id="cbxEM"/></span></li>
                    <li><span class="liLeft">Werkloosheid > 2 jaar</span><span class="liRight"><input type="checkbox" onclick="getData(8)" name="cbxWL" id="cbxWL"/></span></li>
                    <li><span class="liLeft">Armoede, inkomen, arbeid</span><span class="liRight"><input type="checkbox" onclick="getData(9)" name="cbxAI" id="cbxAI"/></span></li>
                    <li><span class="liLeft">Parkeergarages</span><span class="liRight"><input type="checkbox" onclick="getData(10)" name="cbxPG" id="cbxPG"/></span></li>
                    <li><span class="liLeft">Parkinglocaties</span><span class="liRight"><input type="checkbox" onclick="getData(11)" name="cbxPL" id="cbxPL"/></span></li>
                    <li><span class="liLeft">Bioscopen</span><span class="liRight"><input type="checkbox" onclick="getData(12)" name="cbxCI" id="cbxCI"/></span></li>
                    <li><span class="liLeft">Sportcentra</span><span class="liRight"><input type="checkbox" onclick="getData(13)" name="cbxSC" id="cbxSC"/></span></li>
                    <li><span class="liLeft">Bibliotheken</span><span class="liRight"><input type="checkbox" onclick="getData(14)" name="cbxBI" id="cbxBI"/></span></li>
                </ul>
            </div>
            <div id="show-data">
                <div id="output">
                    <div id="map_canvas" style="width:97%;height:300px;"></div>
                </div>
            </div>
            
            <?php if($this->loggedin == 1):?>
            <div id="detail-data">
                <h3>Jouw vergelijking:</h3>
            </div>
            
            <?php else: ?>
            <div id="detail-data">
                <h3>Meer info?</h3>
                <p>Als je registreert, kan je bovenstaande data vergelijken. Op die manier weet je precies waar je naartoe moet gaan!</p>
            </div>
            
            <?php endif; ?>
            
        </section>
        
        <footer class="navbar">
        	<div class="navbar-inner">
            	&copy; Tom Van humbeek, Arteveldehogeschool 2013. <a href="#" title="Disclaimer" class="brand">DISCLAIMER</a>
            </div>
        </footer>
        
        
        
        <div id="view-disclaimer">      
            <h2 data-role="header" class="ui-header ui-bar-a ui-title" role="banner" role="heading" aria-level="1">Da Rulez</h2><span class="closeBtn btn">X</span>
        
            <p>Deze web-app werd gebouwd in opdracht van de Arteveldehogeschool.</p>
            
            <p>Niets - zowel visueel, inhoudelijk als technisch - uit deze web-app mag gebruikt of overnomen geworden, zonder volledig akkoord van de maker.</p>
            
            <p>Web-app gemaakt met:
                <ul>
                    <li>PHP [Zend Framework] met MVC</li>
                    <li>RESTful API: kan JSON/JSON-P genereren</li>
                    <li>MySQL</li>
                    <li>HTML5</li>
                    <li>CSS3</li>
                    <li>jQuery</li>
                    <li>Canvas, Twitter Bootstrap, jQuery Mobile</li>
                    <li>Adobe Photoshop</li>
                </ul>
            </p>
            
            <p>&copy; <a href="http://www.arteveldehogeschool.be" title="Arteveldehogeschool" target="_blank">Arteveldehogeschool Gent</a>, <br/>Tom Van humbeek - 2013</p>
        </div>
        
        <div id="overlay">
        </div>
    </div>
<script type="text/javascript"
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=true"></script>
<script src="/statghent/public/_scripts/js/geolocation.js"></script>