<header>
        <div id="logo">
            <h1><a class="logo title" href="<?php echo $this->url(
                    array('controller'=>'index', 'action' => 'index'),
                    'default',
                    true) ?>" title="GroenGent">GroenGent</a></h1>
            <a href="#" class="btn-user" data-role="button" data-icon="grid" data-iconpos="notext" data-theme="c" data-inline="true">Menu</a>
        </div>
        
        <?php if($this->loggedin == 0):?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'login'),
                        'default',
                        true) ?>" title="Aanmelden" class="btn-primary" data-ajax="false">Aanmelden</a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'register'),
                        'default',
                        true) ?>" title="Registreren" class="btn" data-ajax="false">Registreren</a>
             </div>
         </section>
         
         <section id="nav-mobile">         
             <div id="navbar-mobile" data-role="navbar">
                <ul>
                    <li><a href="#" title="Info" class="ui-btn-active" id="mobileInfo" data-role="button" data-icon="info"></a></li>
                    <li><a href="#" title="Lijst" id="mobileLijst" data-role="button" data-icon="bars"></a></li>
                    <li><a href="#" title="Kaart" id="mobileKaart" data-role="button" data-icon="search"></a></li>
                </ul>
            </div>
         </section>
    <?php else: ?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" class="btn-primary" data-ajax="false"><?php echo "Hallo " . $this->username; ?></a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" class="btn" data-ajax="false">Afmelden</a>
             </div>
         </section>
         
         <section id="nav-mobile">         
             <div id="navbar-mobile" data-role="navbar">
                <ul>
                    <li><a href="#" title="Info" class="ui-btn-active" id="mobileInfo" data-role="button" data-icon="info"></a></li>
                    <li><a href="#" title="Lijst" id="mobileLijst" data-role="button" data-icon="bars"></a></li>
                    <li><a href="#" title="Kaart" id="mobileKaart" data-role="button" data-icon="search"></a></li>
                </ul>
            </div>
         </section>
        <?php endif; ?>
    
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" alt="GroenGent" data-transition="sliceDown"     />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" alt="GroenGent" data-transition="slideInLeft"   />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" alt="GroenGent" data-transition="boxRandom"     />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" alt="GroenGent" data-transition="boxRain"       />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" alt="GroenGent" data-transition="slideInRight"  />
            </div>
        </div>
    </header>

    <div id="menu-mobile">
        <?php if($this->loggedin == 0):?>
            <ul id="mobileOUT">
                <li><a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'login'),
                    'default',
                    true) ?>" title="Aanmelden" data-ajax="false" data-role="button" data-icon="check" data-theme="b" class="txtWhite">Aanmelden</a></li>
                <li><a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'register'),
                    'default',
                    true) ?>" title="Registreren" class="btn" data-ajax="false" data-role="button" data-icon="edit" data-theme="b" class="txtWhite">Registreren</a></li>
                <li><a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'forgotpassword'),
                    'default',
                    true) ?>" title="Wachtwoord vergeten" class="btn" data-ajax="false" data-role="button" data-icon="alert" data-theme="b" class="txtWhite">Wachtwoord vergeten</a></li>

                <li id="mobileDisclaimer"><a href="#" title="Disclaimer" data-role="button" data-inline="true" class="btnFullWidth">Disclaimer</a></li>
                <li id="mobileClose"><a href="#" title="Sluit venster" data-role="button" data-inline="true" class="btnFullWidth">Sluit venster</a></li>
            </ul>
        <?php else: ?>
            <ul id="mobileIN">
                <li><a href="<?php echo $this->url(
                    array('controller'=>'profile'),
                    'default',
                    true) ?>" title="Jouw profiel" class="btn" data-ajax="false" data-role="button" data-icon="bars" data-theme="b" class="txtWhite"><?php echo "Hallo " . $this->username; ?></a></li>
                <li><a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'logout'),
                    'default',
                    true) ?>" title="Aanmelden" data-ajax="false" data-role="button" data-icon="delete" data-theme="b" class="txtWhite">Afmelden</a></li>
                <li id="mobileDisclaimer"><a href="#" title="Disclaimer" data-role="button" data-inline="true" class="btnFullWidth pushDown">Disclaimer</a></li>
                <li id="mobileClose"><a href="#" title="Sluit venster" data-role="button" data-inline="true" class="btnFullWidth">Sluit venster</a></li>
            </ul>
        <?php endif; ?>
    </div>
    
    <div id="container">
        <section id="content">
            <?php if($this->loggedin == 0):?>
                <div id="intro">
                    <h3>Op naar een Groener Gent!</h3>
                    <img src="<?=$this->baseUrl('_assets/img/img-about.png')?>" alt="Over GroenGent"/>
                    <p>GroenGent biedt veel informatie om je Gentse leven makkelijker te maken! Dankzij GroenGent kan je makkelijk opzoeken in welke gebieden van Gent je het beste gaat picknicken, een uitstap doen, een filmpje oppikken of zélfs waar je het best een kot vindt.</p>
                    <p>Registreer en vergelijk onderstaande data met elkaar!</p>
                </div>
            
            
            <!-- LOGGED IN - Compare -->
            <?php else: ?>
            <div id="compare">
                <h3>Je hebt parken geselecteerd:</h3>
                    <div id="cImg">
                        <img src="<?=$this->baseUrl('_assets/img/compare/icon-parken.png')?>" id="c2" alt="Over GroenGent"/>
                        <img src="<?=$this->baseUrl('_assets/img/compare/_arrow.png')?>" id="c1" alt="Over GroenGent"/>
                        <img src="<?=$this->baseUrl('_assets/img/compare/icon-bios.png')?>" id="c3" alt="Over GroenGent"/>
                    </div>
                    <div id="compareTxt">
                        <p>Hmm, een mooie uitstap naar het park, zalig! Met je kleintje een namiddag gaan spelen, of met je partner een wandeling maken.</p>
                        <p>Als je wil, kan je hierna een filmpje meepikken? Klik hieronder op bioscopen!</p>
                    </div>
            </div>
            <?php endif; ?>
            
            <div id="dataFloat" class="ui-grid-a">
                <div id="choose-data" class="ui-block-a">
                    <?php if($this->loggedin == 1):?>
                        <h3>Vergelijk</h3>

                        <?php else: ?>
                        <h3>Weergave</h3>

                    <?php endif; ?>
                        
                    <ul id="selData">
                        <li id="liParken"><span class="liLeft"><a href="#" title="Parken" onclick="getData(1)">Parken</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/1" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liParking"><span class="liLeft"><a href="#" title="Parkings" onclick="getData(2)">Parkings</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/2" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liBibs"><span class="liLeft"><a href="#" title="Bibliotheken" onclick="getData(3)">Bibliotheken</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/3" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liBios"><span class="liLeft"><a href="#" title="Bioscopen" onclick="getData(4)">Bioscopen</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/4" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liApoth"><span class="liLeft"><a href="#" title="Apotheken" onclick="getData(5)">Apotheken</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/5" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liGZCentra"><span class="liLeft"><a href="#" title="Gezondheidscentra" onclick="getData(6)">Gezondheidscentra</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/6" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liDArtsen"><span class="liLeft"><a href="#" title="Dierenartsen" onclick="getData(7)">Dierenartsen</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/7" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liZhuizen"><span class="liLeft"><a href="#" title="Ziekenhuizen" onclick="getData(8)">Ziekenhuizen</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/8" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liBScholen"><span class="liLeft"><a href="#" title="Basisscholen" onclick="getData(9)">Basisscholen</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/9" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liMScholen"><span class="liLeft"><a href="#" title="Secundaire schoole" onclick="getData(10)">Middelbare scholen</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/10" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                        <li id="liKoten"><span class="liLeft"><a href="#" title="Kotzones" onclick="getData(11)">Kotzones</a></span><a href="http://localhost/GroenGentAPI/index.php/datasets/11" title="Bekijk data" data-role="button" class="liRight btn" target="_blank"></a></li>
                    </ul>
                </div>
                <div id="show-data" class="ui-block-b">
                    <div id="output">
                        <div id="map_canvas"></div>
                    </div>
                </div>
            </div>
        </section>
        
        <footer>
        	<div class="">
            	&copy; Tom Van humbeek, Arteveldehogeschool 2013. <a href="#" title="Disclaimer" class="btn">DISCLAIMER</a>
            </div>
        </footer>
        
        <div id="view-disclaimer">     
            <h2 data-role="header" class="ui-header ui-bar-a ui-title sidePadding" role="banner" role="heading" aria-level="1">Disclaimer</h2><span class="closeBtn btn">X</span>
        
            <p>Deze web-app werd gebouwd in opdracht van de Arteveldehogeschool.</p>
            
            <p>Niets - zowel visueel, inhoudelijk als technisch - uit deze web-app mag gebruikt of overnomen geworden, zonder volledig akkoord van de maker.</p>
            
            <p>Web-app gemaakt met:</p>
                <ul>
                    <li>PHP [Zend Framework] met MVC</li>
                    <li>RESTful API: kan JSON/JSON-P genereren</li>
                    <li>MySQL</li>
                    <li>HTML5</li>
                    <li>CSS3</li>
                    <li>jQuery</li>
                    <li>Canvas, Twitter Bootstrap, jQuery Mobile</li>
                    <li>Adobe Photoshop</li>
                </ul>
            
            <p class="txtCenter fontSmall">&copy; <a href="http://www.arteveldehogeschool.be" title="Arteveldehogeschool" target="_blank">Arteveldehogeschool Gent</a>, Tom Van humbeek - 2013</p>
            <a href="#" id="mobileClose" data-role="button" data-inline="true" class="btnFullWidth">Terug</a>
        </div>
    </div>
   <div id="overlay"></div>
<script type="text/javascript"
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqsjbo0JTyqexEzIBOYcolZlo5SBUGrHc&sensor=true"></script>