<header>
    <div id="logo">
    <h1><a class="logo" data-ajax="false" href="<?php echo $this->url(
            array('controller'=>'index', 'action' => 'index'),
            'default',
            true) ?>" title="StatGhent Home">GroenGent</a></h1>
    </div>
    
    <?php if($this->loggedin == 0):?>
    <section id="nav-desktop">
        <div id="buttons-header">
            <a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'register'),
                    'default',
                    true) ?>" class="btn btn-primary" style="margin-top: -8px !important" data-ajax="false">Registreer</a>
         </div>
     </section>
<?php else: ?>
    <section id="nav-desktop">
        <div id="buttons-header">
            <a href="<?php echo $this->url(
                    array('controller'=>'profile'),
                    'default',
                    true) ?>" class="" data-ajax="false"><?php echo $this->username; ?></a>
         </div>
     </section>
<?php endif; ?>

    <div class="slider-wrapper theme-default">
        <div id="slider" class="nivoSlider">
            <img src="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" alt="GroenGent" data-transition="sliceDown"     />
            <img src="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" alt="GroenGent" data-transition="slideInLeft"   />
            <img src="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" alt="GroenGent" data-transition="boxRandom"     />
            <img src="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" alt="GroenGent" data-transition="boxRain"       />
            <img src="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" alt="GroenGent" data-transition="slideInRight"  />
        </div>
    </div>
</header>

<div id="view-disclaimer">      
    <h2 data-role="header" class="ui-header ui-bar-a ui-title" role="banner" role="heading" aria-level="1">Disclaimer</h2><span class="closeBtn btn">X</span>

    <p>Deze web-app werd gebouwd in opdracht van de Arteveldehogeschool.</p>

    <p>Niets - zowel visueel, inhoudelijk als technisch - uit deze web-app mag gebruikt of overnomen geworden, zonder volledig akkoord van de maker.</p>

    <p>Web-app gemaakt met:
        <ul>
            <li>PHP [Zend Framework] met MVC</li>
            <li>RESTful API: kan JSON/JSON-P genereren</li>
            <li>MySQL</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>jQuery</li>
            <li>Canvas, Twitter Bootstrap, jQuery Mobile</li>
            <li>Adobe Photoshop</li>
        </ul>
    </p>

    <p>&copy; <a href="http://www.arteveldehogeschool.be" title="Arteveldehogeschool" target="_blank">Arteveldehogeschool Gent</a>, <br/>Tom Van humbeek - 2013</p>
</div>

<a href="<?php echo $this->url(
            array('controller'=>'index', 'action' => 'index'),
            'default',
            true) ?>" data-ajax="false" data-role="button" data-icon="home" data-iconpos="notext" data-theme="c" data-inline="true" class="btnHome btnMobile"></a>

<div id="container">
    <?php echo $this->form->renderForm(false) ?>
        <h2>Aanmelden</h2>
        <a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'forgotpassword'),
                    'default',
                    true) ?>" title="Forgot password?" class="txtForgot" data-ajax="false">Wachtwoord vergeten?</a>
         <?php foreach ($this->form->getElements() as $element): ?>
            <?php echo $element ?>
         <?php endforeach; ?>
</div>

<footer>
    <div class="">
        &copy; Tom Van humbeek, Arteveldehogeschool 2013. <a href="#" title="Disclaimer" class="btn">DISCLAIMER</a>
    </div>
</footer>

<div id="overlay">
</div>