<section id="page-error">
    <div id="msg-error">
        <h1>Nog iets dat Groener moet!</h1>
        <p>Je bent op een pagina aanbelandt die nog niet bestaat.</p>
        <a href="<?php echo $this->url(
                        array('controller'=>'index', 'action' => 'index'),
                        'default',
                        true) ?>" title="GroenGent Home" class="btnError">Keer terug naar de startpagina.</a>
    </div>
    <img class="img-error" src="<?=$this->baseUrl('_assets/img/404.png')?>" alt="Deze pagina bestaat (nog) niet." />
</section>