<section id="page-error">
    <div id="msg-error">
        <h1>Nog iets dat Groener moet!</h1>
        <p>De server kon jouw aanvraag niet verwerken.</p>
        <a href="<?php echo $this->url(
                        array('controller'=>'index', 'action' => 'index'),
                        'default',
                        true) ?>" title="GroenGent Home" class="btnError btn-success" data-ajax="false">Keer terug naar de startpagina!</a>
    </div>
    <img class="img-error" src="<?=$this->baseUrl('_assets/img/500.png')?>" alt="De server kon jouw aanvraag niet verwerken." />
</section>