<header>
        <div id="logo">
            <h1><a class="logo" href="<?php echo $this->url(
                    array('controller'=>'index', 'action' => 'index'),
                    'default',
                    true) ?>" data-ajax="false" title="GroenGent Home">GroenGent</a></h1>
            <a href="#" class="btn-user frontOpacity" data-role="button" data-icon="grid" data-iconpos="notext" data-theme="c" data-inline="true">Menu</a>
        </div>
        <section id="nav-desktop">
            <div id="buttons-header" class="allBlack">
                <a href="<?php echo $this->url(
                    array('controller'=> 'profile', 'action'=>'index'),
                    'default',
                    true) ?>" data-ajax="false" class="btn txtBlack" title="Annuleer">Annuleer</a>
                <a href="<?php echo $this->url(
                    array('controller'=>'account', 'action' => 'logout'),
                    'default',
                    true) ?>" data-ajax="false" class="btn" title="Afmelden">Afmelden</a>
             </div>
         </section>
         
         
        <div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo01.jpg')?>" alt="GroenGent" data-transition="sliceDown"     />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo02.jpg')?>" alt="GroenGent" data-transition="slideInLeft"   />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo03.jpg')?>" alt="GroenGent" data-transition="boxRandom"     />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo04.jpg')?>" alt="GroenGent" data-transition="boxRain"       />
                <img src="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" data-thumb="<?=$this->baseUrl('_assets/img/nivo/nivo05.jpg')?>" alt="GroenGent" data-transition="slideInRight"  />
            </div>
        </div>
    </header>

    <div id="menu-mobile">
            <ul>
                <li id="mobileDisclaimer" class="txtBlack"><a href="#" title="Disclaimer" data-role="button" data-inline="true" class="btnFullWidth txtBlack">Disclaimer</a></li>
                <li id="mobileClose"><a href="#" title="Sluit venster" data-role="button" data-inline="true" class="btnFullWidth backOpacity">Sluit venster</a></li>
            </ul>
    </div>

    <?php echo $this->form; ?>

<footer>
        <div class="">
        &copy; Tom Van humbeek, Arteveldehogeschool 2013. <a href="#" title="Disclaimer" class="btn frontOpacity">DISCLAIMER</a>
    </div>
</footer>

<div id="view-disclaimer">     
    <h2 data-role="header" class="ui-header ui-bar-a ui-title sidePadding" role="banner" role="heading" aria-level="1">Disclaimer</h2><span class="closeBtn backOpacity btn">X</span>

    <p>Deze web-app werd gebouwd in opdracht van de Arteveldehogeschool.</p>

    <p>Niets - zowel visueel, inhoudelijk als technisch - uit deze web-app mag gebruikt of overnomen geworden, zonder volledig akkoord van de maker.</p>

    <p>Web-app gemaakt met:</p>
        <ul>
            <li>PHP [Zend Framework] met MVC</li>
            <li>RESTful API: kan JSON/JSON-P genereren</li>
            <li>MySQL</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>jQuery</li>
            <li>Canvas, Twitter Bootstrap, jQuery Mobile</li>
            <li>Adobe Photoshop</li>
        </ul>

    <p class="txtCenter fontSmall">&copy; <a href="http://www.arteveldehogeschool.be" title="Arteveldehogeschool" target="_blank">Arteveldehogeschool Gent</a>, Tom Van humbeek - 2013</p>
    <a href="#" id="mobileClose" data-role="button" data-inline="true" class="btnFullWidth">Terug</a>
</div>
        
<div id="overlay">
</div>