<header>
		<div id="logo">
        	<h1><a class="logo" href="<?php echo $this->url(
                        array('controller'=>'index', 'action' => 'index'),
                        'default',
                        true) ?>" title="GroenGent Home">GroenGent</a></h1>
		</div>
        <?php if($this->loggedin == 0):?>
        <section id="nav-desktop">
         </section>
         
        <section id="nav-tablet">
         </section>
         
         <section id="nav-mobile">         
         	<a href="#" title="Navigation menu" data-icon="grid" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" class="menuBtn ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text"></span>
                    <span class="ui-icon ui-icon-grid ui-icon-shadow" style="margin: -4px 0 0 -4px;"></span>
                </span>
            </a>
         
         <div id="buttons-header-mobile">
         		<a href="<?php echo $this->url(
                            array('controller'=>'account', 'action' => 'login'),
                            'default',
                        true) ?>" data-icon="check" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="loginMobileBtn" class="btn btn-login ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text">Aanmelden</span>
                        <span class="ui-icon ui-icon-check ui-icon-shadow"></span>
                    </span>
                </a>
                
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'register'),
                        'default',
                        true) ?>" data-icon="edit" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="registerMobileBtn" class="btn btn-register ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text">Registreer</span>
                        <span class="ui-icon ui-icon-edit ui-icon-shadow"></span>
                    </span>
                </a>
                
                <a href="#" title="Disclaimer" id="mobileDisclaimerBtn" data-icon="info" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="#styleMobile" class="btn btn-disclaimer ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                    <span class="ui-btn-inner">
                        <span class="ui-btn-text">Disclaimer</span>
                        <span class="ui-icon ui-icon-info ui-icon-shadow"></span>
                    </span>
                </a>
             </div>
         </section>
    <?php else: ?>
        <section id="nav-desktop">
            <div id="buttons-header">
                <a href="<?php echo $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" class="btn btn-primary btn-profile"><?php echo "Hello " . $this->username; ?></a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" class="btn btn-primary btn-profile">Afmelden</a>
                
             </div>
         </section>
         
        <section id="nav-tablet">
            <div id="buttons-header-tablet">
                <a href="<?php echo "Hello " . $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" class="btn btn-login"><?php echo "Hello " . $this->username; ?></a>
                <a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" class="btn btn-register">Afmelden</a>
                
                
             </div>
         </section>
         
         <section id="nav-mobile">         
         	<a href="#" title="Navigation menu" data-icon="grid" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" class="menuBtn ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                <span class="ui-btn-inner">
                    <span class="ui-btn-text"></span>
                    <span class="ui-icon ui-icon-grid ui-icon-shadow" style="margin: -4px 0 0 -4px;"></span>
                </span>
            </a>
         
         <div id="buttons-header-mobile">
         		<a href="<?php echo "Hallo " . $this->url(
                        array('controller'=>'profile'),
                        'default',
                        true) ?>" data-icon="check" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="profileMobileBtn" class="btn btn-profile ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text"><?php echo "Hallo " . $this->username; ?></span>
                        <span class="ui-icon ui-icon-check ui-icon-shadow"></span>
                    </span>
                </a>
         		<a href="<?php echo $this->url(
                        array('controller'=>'account', 'action' => 'logout'),
                        'default',
                        true) ?>" data-icon="check" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="profileMobileBtn" class="btn btn-profile ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                	<span class="ui-btn-inner">
                    	<span class="ui-btn-text">Afmelden</span>
                        <span class="ui-icon ui-icon-check ui-icon-shadow"></span>
                    </span>
                </a>
                
                             
                <a href="#" title="Disclaimer" id="mobileDisclaimerBtn" data-icon="info" data-role="button" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" id="#styleMobile" class="btn btn-disclaimer ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-left ui-btn-up-c">
                    <span class="ui-btn-inner">
                        <span class="ui-btn-text">Disclaimer</span>
                        <span class="ui-icon ui-icon-info ui-icon-shadow"></span>
                    </span>
                </a>
             </div>
         </section>
    <?php endif; ?>
    
    </header>

<div id="container">
        <section id="content-profile">

<h1>Dag <?php echo $this->username ?>!</h1>
<p class="borderBtm">Hieronder kan je je gegevens bekijken en aanpassen.</p>
<ul id="profileEdit">
    <li><span class="txtBold">Naam:</span> <span class="txtVal"><?php echo $this->firstname ?> <?php echo $this->surname ?></span></li>
    <li><span class="txtBold">E-mail:</span> <span class="txtVal"><?php echo $this->email ?></span></li>
    <li><span class="txtBold">Geslacht:</span> <span class="txtVal"><?php echo ($this->sex=='m'?"Man":"Vrouw") ;?></span></li>

    <?php if (!empty($this->description)):?>
        <li><span class="txtBold">Over jou:</span> <span class="txtVal"><?php echo $this->description ?></span></li>
    <?php endif; ?> 

    <!-- Btn Homepage -->
    <br/>
    <?php if (!empty($this->website)):?>
    <li class="marginTop"><span class="txtBold">Jouw website:</span> <span class="txtVal"><a href="http://<?php echo $this->website; ?>" title="<?php echo $this->website; ?>" target="_blank"><?php echo $this->website; ?></a></span></li>
    <?php endif; ?> 

    <?php if ($this->hasimage):?>
        <li><img src="http:///GroenGent/public/images/<?php echo $this->image ;?>" alt="<?php echo $this->username ?>" /></li>
    <?php endif; ?>
</ul>
<img src="<?=$this->baseUrl('_assets/img/icons/icon-profile.png')?>" class="icon-profile"/>
    <div id="btnsProfile">
        <!-- Btn Edit -->
        <a href="<?php echo $this->url(
            array('controller'=>'profile', 'action' => 'edit'),
            'default',
            true) ?>" class="btnGreen">Wijzig profiel</a>
            
        <!-- Btn Cancel -->
        <a href="<?php echo $this->url(
            array('controller'=>'index', 'action' => 'index'),
            'default',
            true) ?>" class="btnGreen">Annuleren</a>

        <!-- Btn Logout -->
        <a href="<?php echo $this->url(
            array('controller'=>'account', 'action' => 'logout'),
            'default',
            true) ?>" class="btnGrey fRight">Afmelden</a>
        </section>
    </div>
</div>